version: '3.8'

services:
  db:
    image: postgres:15
    container_name: marathon-db
    environment:
      
      POSTGRES_DB: Marathon_DB
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: guusvanmeel/marathon-backend:latest
    container_name: marathon-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
  frontend:
    image: guusvanmeel/marathon-frontend:latest
    container_name: marathon-frontend
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres_data: