spring.application.name=Marathon-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/Marathon_DB
spring.datasource.username=postgres
spring.datasource.password=Stepkapsom.4

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
